poses:
  left_arm:
    ready:
      19: 135
      20: 80
      21: 90
      22: 170
      23: 90
    talking:
      19: 130
      20: 50
      21: 90
      22: 150
      23: 90
  left_hand:
    ready:
      24: 180
      25: 180
      26: 180
      27: 120
      28: 180
  right_arm:
    ready:
      3: 135
      4: 80
      5: 80
      6: 170
      7: 90
    talking:
      3: 140
      4: 50
      5: 80
      6: 140
      7: 30
  right_hand:
    ready:
      8: 180
      9: 180
      10: 180
      11: 180
      12: 180
